name: Build and Release

on:
  push:
    tags:
      - "*"
  workflow_dispatch:

env:
  PACKAGE_NAME: luci-app-passwall2
  CACHE_DIR: ~/cache

jobs:
  release:
    name: Build ${{ matrix.arch }}-${{ matrix.sdk }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch:
          - aarch64_cortex-a53
          # - aarch64_cortex-a72
          # - aarch64_generic
          # - arm_arm1176jzf-s_vfp
          # - arm_arm926ej-s
          # - arm_cortex-a15_neon-vfpv4
          # - arm_cortex-a5_vfpv4
          # - arm_cortex-a7
          # - arm_cortex-a7_neon-vfpv4
          # - arm_cortex-a8_vfpv3
          # - arm_cortex-a9
          # - arm_cortex-a9_neon
          # - arm_cortex-a9_vfpv3-d16
          # - arm_fa526
          # - arm_mpcore
          # - arm_xscale
          # - i386_pentium-mmx
          # - i386_pentium4
          # - mips64_octeonplus
          # - mips_24kc
          # - mips_4kec
          # - mips_mips32
          # - mipsel_24kc
          # - mipsel_24kc_24kf
          # - mipsel_74kc
          # - mipsel_mips32
          # - x86_64
        sdk:
          - openwrt-22.03
          - SNAPSHOT

    env:
      SDK_URL_PATH: ${{ matrix.sdk_url_path }}
      SDK_NAME: ${{ matrix.sdk_name }}
      CCACHE_DIR: ~/.ccache
      CONFIG_CCACHE: y
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Building packages
        uses: sbwml/openwrt-gh-action-sdk@main
        env:
          ARCH: ${{ matrix.arch }}-${{ matrix.sdk }}
          FEEDNAME: packages_ci
          PACKAGES: luci-app-passwall2
          NO_REFRESH_CHECK: true
          V: s

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.arch }}-${{ matrix.sdk }}
          path: bin/packages/${{ matrix.arch }}/packages_ci/*.[ai]pk

      - name: Create compress files
        run: |
          #tar -zcvf passwall2-${{ matrix.sdk }}-${{ matrix.arch }}.tar.gz -C bin/packages/${{ matrix.arch }}/ packages_ci
          zip -j passwall2-${{ matrix.arch }}-${{ matrix.sdk }}.zip bin/packages/${{ matrix.arch }}/packages_ci/*
          echo "build_time=$(date '+%Y年%m月%d日%H:%M:%S' | jq -sRr @uri)" >> $GITHUB_ENV

      - name: Release and Upload Assets
        uses: softprops/action-gh-release@v2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ env.TAG }}
          files: passwall2-${{ matrix.arch }}-${{ matrix.sdk }}.zip